[tox]
min_version = 4
env_list = py3{9,10,11,12}-tests, coverage-report

[testenv]
package = wheel
wheel_build_env = .pkg
extras =
    tests: tests
commands =
    tests: pytest {posargs}

[testenv:py3{9,12}-tests]
set_env =
    py312: COVERAGE_CORE=sysmon
deps =
    coverage[toml]
commands = coverage run -m pytest {posargs}

[testenv:coverage-report]
# Keep in-sync with .python-version
base_python = py312
deps = coverage[toml]
skip_install = true
parallel_show_output = true
# Keep in-sync with test env definition above.
depends = py3{9,12}-tests
commands =
    coverage combine
    coverage report
