name: CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write
    outputs:
      released: ${{ steps.version.outputs.released }}
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - name: Setup | Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}
      - name: Setup | Force correct release branch
        run: |
          git checkout -B ${{ github.ref_name }} ${{ github.sha }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install python-semantic-release>=9.16.1
      - name: Version
        id: version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release version
          # Capture the outputs
          echo "released=$(semantic-release inspect --released)" >> $GITHUB_OUTPUT
          echo "version=$(semantic-release inspect --version)" >> $GITHUB_OUTPUT
          echo "tag=v$(semantic-release inspect --version)" >> $GITHUB_OUTPUT
      - name: Publish
        if: steps.version.outputs.released == 'true'
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: semantic-release publish
