name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches: [main]
    tags: ["*"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    environment: Testing
    needs:
      - ci

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
          cache: 'pip'
      - uses: hynek/setup-cached-uv@v2
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9.8.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build project
        run: hatch build
      - name: Publish package distributions to Test PyPI
        if: steps.release.outputs.released == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
      - name: Publish package distributions to GitHub Releases
        if: steps.release.outputs.released == 'true'
        uses: python-semantic-release/upload-to-gh-release@v9.8.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}
