name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build-package:
    name: Build & verify package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - uses: hynek/build-and-inspect-python-package@v2
        id: baipp
        with:
          attest-build-provenance-github: 'true'

  pypi-release:
    name: Release to PyPI
    needs: build-package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/extended-data-types/
    permissions:
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
