name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run Tox
        uses: tox-dev/tox-gh@v2
        with:
          python-versions: "3.7, 3.8, 3.9, 3.10, 3.11, 3.12"
